# ---------------------------------------------
# Variables
# ---------------------------------------------
variable "project" {
  type = string
}
variable "environment" {
  type = string
}
variable "private_subnet_id" {
  type = string
}
variable "private_subnet_id-1c" {
  type = string
}

variable "fargate_frontend_sg_id" {
  type = string
}
variable "fargate_backend_sg_id" {
  type = string
}

variable "ecs_task_execution_role_arn" {
  type = string
}
variable "ecs_infrastructure_role_for_load_balancers_arn" {
  type = string
}

# ============================
# Frontend
# ============================

variable "frontend_target_group_1_arn" {
  type        = string
  description = "Frontend Blue target group ARN"
}

variable "frontend_target_group_2_arn" {
  type        = string
  description = "Frontend Green target group ARN"
}

variable "frontend_production_listener_rule_arn" {
  type        = string
  description = "Frontend production listener rule ARN"
}

variable "frontend_test_listener_rule_arn" {
  type        = string
  description = "Frontend test listener rule ARN"
}

# ============================
# Backend
# ============================

variable "backend_target_group_1_arn" {
  type        = string
  description = "Backend Blue target group ARN"
}

variable "backend_target_group_2_arn" {
  type        = string
  description = "Backend Green target group ARN"
}

variable "backend_production_listener_rule_arn" {
  type        = string
  description = "Backend production listener rule ARN"
}

variable "backend_test_listener_rule_arn" {
  type        = string
  description = "Backend test listener rule ARN"
}
# ============================
# image tag
# ============================

variable "frontend_image_tag" {
  type        = string
  description = "Frontend Docker Image Tag"
  default     = "latest"
}
variable "backend_image_tag" {
  type        = string
  description = "Backend Docker Image Tag"
  default     = "latest"
}

# ============================
# env
# ============================
variable "aws_rds_cluster_aurora_cluster_endpoint" {
  type        = string
  description = "Aurora Cluster Writer Endpoint"
}
variable "aws_rds_cluster_aurora_cluster_master_username" {
  type        = string
  description = "Aurora Master Username"
}

variable "aws_rds_cluster_aurora_cluster_database_name" {
  type        = string
  description = "Aurora Database Name"
}

variable "aws_rds_cluster_aurora_cluster_master_user_secret_arn" {
  type        = string
  description = "Secrets Manager ARN generated by Aurora"
}