# modules/aurora/output.tf
output "aws_rds_cluster_aurora_cluster_endpoint" {
  description = "Aurora Cluster Writer Endpoint"
  value       = aws_rds_cluster.aurora_cluster.endpoint
}

output "aws_rds_cluster_aurora_cluster_master_username" {
  description = "Aurora Master Username"
  value       = aws_rds_cluster.aurora_cluster.master_username
}

output "aws_rds_cluster_aurora_cluster_database_name" {
  description = "Aurora Database Name"
  value       = aws_rds_cluster.aurora_cluster.database_name
}

output "aws_rds_cluster_aurora_cluster_master_user_secret_arn" {
  description = "Secrets Manager ARN generated by Aurora"
  value       = aws_rds_cluster.aurora_cluster.master_user_secret[0].secret_arn
}